package com.tsanet.application.setup;

public final class TestScenarioDataCatalog {
    public static final long ACME_COMPANY_ID = 1L;
    public static final long BETA_COMPANY_ID = 2L;

    public static final long ACME_CONTACT_DOCUMENT_ID = 1L;
    public static final long BETA_CONTACT_DOCUMENT_ID = 2L;
    public static final long ACME_DOCUMENT_VERSION_ID = 1L;
    public static final long BETA_DOCUMENT_VERSION_ID = 2L;

    public static final long DEMO_COMMUNITY_ID = 1L;
    public static final long ACME_COMPANY_COMMUNITY_ID = 1L;
    public static final long BETA_COMPANY_COMMUNITY_ID = 2L;

    public static final long ADMIN_USER_ID = 2L;
    public static final String ADMIN_USER_EMAIL = "admin@tsanet.org";
    public static final long API_USER_ID = 9587L;
    public static final String API_USER_EMAIL = "api@appko.com";

    public static final String BETA_SCENARIO_USER_EMAIL = ADMIN_USER_EMAIL;

    public static final String ACME_OPEN_REQUEST_NUMBER = "ACME-OUT-001";
    public static final String ACME_OPEN_REQUEST_SUMMARY = "Open collaboration request";

    public static final String ACME_ACCEPTED_REQUEST_NUMBER = "ACME-OUT-002";
    public static final String ACME_ACCEPTED_REQUEST_SUMMARY = "Accepted collaboration request";

    public static final String ACME_REJECTED_REQUEST_NUMBER = "ACME-OUT-003";
    public static final String ACME_REJECTED_REQUEST_SUMMARY = "Rejected collaboration request";

    public static final String BETA_SCENARIO_NOTE_PREFIX = "Beta scenario note:";
    public static final String DEFAULT_NOTE_PRIORITY = "MEDIUM";

    public static String betaScenarioNoteSummary(String requestSummary) {
        return BETA_SCENARIO_NOTE_PREFIX + " " + requestSummary;
    }

    public static final String SCENARIO_ATTACHMENT_FILE_NAME = "scenario-attachment.txt";
    public static final String SCENARIO_ATTACHMENT_DESCRIPTION = "Integration scenario test attachment";
    public static final String SCENARIO_ATTACHMENT_CONTENT =
        "TSANet integration demo attachment file generated by CollaborationRequestAttachmentsScenario.";

    public static final String SCENARIO_WEBHOOK_CALLBACK_URL = "https://example.com/tsanet/demo-webhook";
    public static final String WEBHOOK_EVENT_COLLAB_REQUEST_CREATED = "collaboration-request.created";
    public static final String WEBHOOK_EVENT_NOTE_CREATED = "note.created";

    public static final String COLLABORATION_REQUEST_STATUS_ACCEPTED = "ACCEPTED";
    public static final String CASE_RESPONSE_TYPE_APPROVAL = "APPROVAL";

    public static final String BETA_APPROVAL_ENGINEER_NAME = "Beta Integration Engineer";
    public static final String BETA_APPROVAL_ENGINEER_EMAIL = ADMIN_USER_EMAIL;
    public static final String BETA_APPROVAL_ENGINEER_PHONE = "+1-555-0100";
    public static final String BETA_APPROVAL_NEXT_STEPS =
        "Approved during integration scenario; Beta will proceed with investigation.";

    public static final int CONTACT_FORM_CUSTOM_FIELD_COUNT = 3;

    private TestScenarioDataCatalog() {
    }
}
